import { Movie } from "./types/types";

export const movies: Movie[] = [{
    id: '1',
    title: 'The Batman',
    image: 'https://i5.walmartimages.com/asr/9fea481e-c606-4ed7-b94c-3e1a020a3dd7.d3fca58269d598e0c600813db6eb07b4.jpeg',
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption and question his familys involvement.',
    genreList: ['Action', 'Thriller', 'Horror', 'Comedy', 'Romance', 'Satire', 'Black Comedy'],
    streamingList: ['netflix', 'hulu', 'prime'],
    releaseYear: '2021',
}, {
    id: '2',
    title: 'Bladerunner 2049',
    image: 'https://www.originalfilmart.com/cdn/shop/products/blade_runner_2049_2017_advance_original_film_art_efd5b98a-e898-4999-810d-1a0448114ff4_600x.jpg?v=1640043899',
    description: 'Young Blade Runner Ks discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, whos been missing for thirty years.',
    genreList: ['Adventure', 'Drama'],
    streamingList: ['prime', 'netflix'],
    releaseYear: '2016',
}, {
    id: '3',
    title: 'Isle of Dogs',
    image: 'https://m.media-amazon.com/images/M/MV5BZDQwOWQ2NmUtZThjZi00MGM0LTkzNDctMzcyMjcyOGI1OGRkXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg',
    description: 'An outbreak of dog flu has spread through the city of Megasaki, Japan, and Mayor Kobayashi has demanded all dogs to be sent to Trash Island. On the island, a young boy named Atari sets out to find his lost dog, Spots, with the help of five other dogs... with many obstacles along the way.',
    genreList: ['Adventure', 'Comedy'],
    streamingList: ['max', 'hulu'],
    releaseYear: '2015',
}, {
    id: '4',
    title: 'The Prestige',
    image: 'https://i.etsystatic.com/35760518/r/il/bea25f/3992841199/il_570xN.3992841199_7lad.jpg',
    description: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    genreList: ['Action', 'Mystery'],
    streamingList: ['hulu', 'prime'],
    releaseYear: '2021',
}, {
    id: '5',
    title: 'Spider-Man: Into the Spider-Verse',
    image: 'https://i.etsystatic.com/18242346/r/il/0e640a/3105585198/il_fullxfull.3105585198_gvkg.jpg',
    description: 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    genreList: ['Adventure', 'Animated'],
    streamingList: ['prime'],
    releaseYear: '2016',
}, {
    id: '6',
    title: 'In Bruges',
    image: 'https://i.ebayimg.com/images/g/NQgAAOSw4wVeemGc/s-l1600.jpg',
    description: 'After a job gone wrong, hitman Ray and his partner await orders from their ruthless boss in Bruges, Belgium, the last place in the world Ray wants to be.',
    genreList: ['Crime', 'Drama'],
    streamingList: ['max', 'netflix', 'prime', 'hulu'],
    releaseYear: '2015',
}, ]